apiVersion: v1
kind: Service
metadata:
  name: microdegree-service
spec:
  selector:
    app: microdegree
  type: NodePort
  ports:
    - protocol: TCP
      port: 80        # Port inside cluster
      targetPort: 8080 # Port your container listens on
      nodePort: 31234  # External port
